[tool.black]
line-length = 100
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox,
  | _build,
  | bin,
  | docs,
  | notebooks/private,
  | venv
)/
'''

[tool.isort]
atomic = true
float_to_top = true
include_trailing_comma = true
line_length = 100
multi_line_output = 3
skip = ["notebooks/private/", "venv/"]
