[tool.black]
line-length = 100
target-version = ['py311']
extend-exclude = '(notebooks/private)'

[tool.isort]
atomic = true
float_to_top = true
include_trailing_comma = true
line_length = 100
multi_line_output = 3
skip = ["notebooks/private/", "venv/"]
