[tool.black]
line-length = 100
target-version = ['py311']
extend-exclude = '(notebooks/private)'

[tool.coverage.run]
omit = [
    "./tests/*",
    "./venv/*",
]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["F", "E", "W", "I", "UP", "S", "B", "T20", "RUF"]
ignore = ["E501", "B904", "B007", "S308", "S113", "S314"]
unfixable = ["F401", "F841"]

[tool.ruff.isort]
known-first-party = ["bmds"]

[tool.ruff.per-file-ignores]
"test_*.py" = ["S101", "S106"]
"notebooks/*.py" = ["T201"]
