default_rules = [
    {
        "failure_bin": 2,
        "description": "A BMD value was successfully calculated.",
        "name": "BMD",
        "threshold": None,
        "continuous_on": True,
        "dichotomous_on": True,
        "cancer_dichotomous_on": True,
    },
    {
        "failure_bin": 2,
        "description": "A BMDL value was successfully calculated.",
        "name": "BMDL",
        "threshold": None,
        "continuous_on": True,
        "dichotomous_on": True,
        "cancer_dichotomous_on": True,
    },
    {
        "failure_bin": 0,
        "description": "A BMDU value was successfully calculated.",
        "name": "BMDU",
        "threshold": None,
        "continuous_on": False,
        "dichotomous_on": False,
        "cancer_dichotomous_on": True,
    },
    {
        "failure_bin": 2,
        "description": "An AIC value was successfully calculated.",
        "name": "AIC",
        "threshold": None,
        "continuous_on": True,
        "dichotomous_on": True,
        "cancer_dichotomous_on": True,
    },
    {
        "failure_bin": 1,
        "description": "A residual of interest can be calculated",
        "name": "Residual of interest exists",
        "threshold": None,
        "continuous_on": True,
        "dichotomous_on": True,
        "cancer_dichotomous_on": True,
    },
    {
        "failure_bin": 1,
        "description": "The correct variance model was used (based on p-test #2).",
        "name": "Variance Type",
        "threshold": 0.1,
        "continuous_on": True,
        "dichotomous_on": False,
        "cancer_dichotomous_on": False,
    },
    {
        "failure_bin": 1,
        "description": "The variance model appropriately captures the variance of the dataset being modeled (based on p-test #3).",
        "name": "Variance Fit",
        "threshold": 0.1,
        "continuous_on": True,
        "dichotomous_on": False,
        "cancer_dichotomous_on": False,
    },
    {
        "failure_bin": 1,
        "description": "The mean model is appropriately modeling the dataset, based on the global-goodness-of-fit (p-test #4).",
        "name": "GGOF",
        "threshold": 0.1,
        "continuous_on": True,
        "dichotomous_on": True,
        "cancer_dichotomous_on": False,
    },
    {
        "failure_bin": 1,
        "description": "The mean model is appropriately modeling the dataset, based on the global-goodness-of-fit (p-test #4).",
        "name": "GGOF (Cancer)",
        "threshold": 0.05,
        "continuous_on": False,
        "dichotomous_on": False,
        "cancer_dichotomous_on": True,
    },
    {
        "failure_bin": 1,
        "description": "The ratio between the BMD and BMDL values is large, indicating a large spread of estimates in the range of interest (warning).",
        "name": "BMD/BMDL (serious)",
        "threshold": 20,
        "continuous_on": True,
        "dichotomous_on": True,
        "cancer_dichotomous_on": True,
    },
    {
        "failure_bin": 0,
        "description": "The ratio between the BMD and BMDL values is large, indicating a large spread of estimates in the range of interest (caution).",
        "name": "BMD/BMDL (warning)",
        "threshold": 5,
        "continuous_on": True,
        "dichotomous_on": True,
        "cancer_dichotomous_on": True,
    },
    {
        "failure_bin": 1,
        "description": "The absolute value of the residual at the dose closest to the BMD is large, which means the model may not be estimating well in this range.",
        "name": "Residual of Interest",
        "threshold": 2,
        "continuous_on": True,
        "dichotomous_on": True,
        "cancer_dichotomous_on": True,
    },
    {
        "failure_bin": 0,
        "description": "The model output file included additional warnings.",
        "name": "Warnings",
        "threshold": None,
        "continuous_on": True,
        "dichotomous_on": True,
        "cancer_dichotomous_on": True,
    },
    {
        "failure_bin": 0,
        "description": "The BMD estimate is higher than the maximum dose modeled, thus the model is extrapolating a result.",
        "name": "BMD higher",
        "threshold": 1,
        "continuous_on": True,
        "dichotomous_on": True,
        "cancer_dichotomous_on": True,
    },
    {
        "failure_bin": 1,
        "description": "The BMDL estimate is higher than the maximum dose modeled, thus the model is extrapolating a result.",
        "name": "BMDL higher",
        "threshold": 1,
        "continuous_on": True,
        "dichotomous_on": True,
        "cancer_dichotomous_on": True,
    },
    {
        "failure_bin": 0,
        "description": "The BMD estimate is lower than the lowest non-zero dose (caution).",
        "name": "Low BMD (warning)",
        "threshold": 3,
        "continuous_on": True,
        "dichotomous_on": True,
        "cancer_dichotomous_on": True,
    },
    {
        "failure_bin": 0,
        "description": "The BMDL estimate is lower than the lowest non-zero dose (caution).",
        "name": "Low BMDL (warning)",
        "threshold": 3,
        "continuous_on": True,
        "dichotomous_on": True,
        "cancer_dichotomous_on": True,
    },
    {
        "failure_bin": 1,
        "description": "The BMD estimate is lower than the lowest non-zero dose (warning).",
        "name": "Low BMD (serious)",
        "threshold": 10,
        "continuous_on": True,
        "dichotomous_on": True,
        "cancer_dichotomous_on": True,
    },
    {
        "failure_bin": 1,
        "description": "The BMDL estimate is lower than the lowest non-zero dose (warning).",
        "name": "Low BMDL (serious)",
        "threshold": 10,
        "continuous_on": True,
        "dichotomous_on": True,
        "cancer_dichotomous_on": True,
    },
    {
        "failure_bin": 1,
        "description": "The absolute value of the residual at the control is large, which is often used to estimate the BMR. Thus, the BMR estimate may be inaccurate.",
        "name": "Control residual",
        "threshold": 2,
        "continuous_on": True,
        "dichotomous_on": False,
        "cancer_dichotomous_on": False,
    },
    {
        "failure_bin": 1,
        "description": "The standard deviation estimate at the control is different the the reported deviation, which is often used to estimate the BMR. Thus, the BMR estimate may be inaccurate.",
        "name": "Control stdev",
        "threshold": 1.5,
        "continuous_on": True,
        "dichotomous_on": False,
        "cancer_dichotomous_on": False,
    }
]
