from ... import constants
from . import rules

DEFAULT_RULE_ARGS = {
    "gof": {
        "threshold": 0.1,
        "failure_bin": constants.BIN_NO_CHANGE,
        "enabled_nested": True,
        "enabled_continuous": True,
        "enabled_dichotomous": True,
    },
    "dof_zero": {
        "threshold": None,
        "failure_bin": constants.BIN_NO_CHANGE,
        "enabled_nested": True,
        "enabled_continuous": True,
        "enabled_dichotomous": True,
    },
    "high_bmd": {
        "threshold": 1,
        "failure_bin": constants.BIN_WARNING,
        "enabled_nested": True,
        "enabled_continuous": True,
        "enabled_dichotomous": True,
    },
    "warnings": {
        "threshold": None,
        "failure_bin": constants.BIN_WARNING,
        "enabled_nested": False,
        "enabled_continuous": False,
        "enabled_dichotomous": False,
    },
    "high_bmdl": {
        "threshold": 1,
        "failure_bin": constants.BIN_WARNING,
        "enabled_nested": True,
        "enabled_continuous": True,
        "enabled_dichotomous": True,
    },
    "roi_large": {  # TODO residuals not available for cont
        "threshold": 2,
        "failure_bin": constants.BIN_NO_CHANGE,
        "enabled_nested": True,
        "enabled_continuous": False,
        "enabled_dichotomous": True,
    },
    "gof_cancer": {
        "threshold": 0.05,
        "failure_bin": constants.BIN_NO_CHANGE,
        "enabled_nested": False,
        "enabled_continuous": False,
        "enabled_dichotomous": True,
    },
    "aic_missing": {
        "threshold": None,
        "failure_bin": constants.BIN_FAILURE,
        "enabled_nested": True,
        "enabled_continuous": True,
        "enabled_dichotomous": True,
    },
    "bmd_missing": {
        "threshold": None,
        "failure_bin": constants.BIN_FAILURE,
        "enabled_nested": True,
        "enabled_continuous": True,
        "enabled_dichotomous": True,
    },
    "roi_missing": {  # TODO residuals not available for cont
        "threshold": None,
        "failure_bin": constants.BIN_FAILURE,
        "enabled_nested": True,
        "enabled_continuous": False,
        "enabled_dichotomous": True,
    },
    "bmdl_missing": {
        "threshold": None,
        "failure_bin": constants.BIN_FAILURE,
        "enabled_nested": True,
        "enabled_continuous": True,
        "enabled_dichotomous": True,
    },
    "bmdu_missing": {
        "threshold": None,
        "failure_bin": constants.BIN_WARNING,
        "enabled_nested": False,
        "enabled_continuous": False,
        "enabled_dichotomous": False,
    },
    "low_bmd_fail": {
        "rule_name": "BMD lower than lowest dose (serious)",
        "threshold": 10,
        "failure_bin": constants.BIN_NO_CHANGE,
        "enabled_nested": True,
        "enabled_continuous": True,
        "enabled_dichotomous": True,
    },
    "low_bmd_warn": {
        "rule_name": "BMD lower than lowest dose (warning)",
        "threshold": 3,
        "failure_bin": constants.BIN_WARNING,
        "enabled_nested": True,
        "enabled_continuous": True,
        "enabled_dichotomous": True,
    },
    "variance_fit": {
        "threshold": 0.05,
        "failure_bin": constants.BIN_NO_CHANGE,
        "enabled_nested": False,
        "enabled_continuous": True,
        "enabled_dichotomous": False,
    },
    "low_bmdl_fail": {
        "rule_name": "BMDL lower than lowest dose (serious)",
        "threshold": 10,
        "failure_bin": constants.BIN_NO_CHANGE,
        "enabled_nested": True,
        "enabled_continuous": True,
        "enabled_dichotomous": True,
    },
    "low_bmdl_warn": {
        "rule_name": "BMDL lower than lowest dose (warning)",
        "threshold": 3,
        "failure_bin": constants.BIN_WARNING,
        "enabled_nested": True,
        "enabled_continuous": True,
        "enabled_dichotomous": True,
    },
    "variance_type": {
        "threshold": 0.05,
        "failure_bin": constants.BIN_WARNING,
        "enabled_nested": False,
        "enabled_continuous": True,
        "enabled_dichotomous": False,
    },
    "control_stdev_fit": {
        "threshold": 1.5,
        "failure_bin": constants.BIN_WARNING,
        "enabled_nested": False,
        "enabled_continuous": True,
        "enabled_dichotomous": False,
    },
    "bmd_bmdl_ratio_fail": {
        "rule_name": "Ratio of BMD/BMDL (serious)",
        "threshold": 20,
        "failure_bin": constants.BIN_NO_CHANGE,
        "enabled_nested": True,
        "enabled_continuous": True,
        "enabled_dichotomous": True,
    },
    "bmd_bmdl_ratio_warn": {
        "rule_name": "Ratio of BMD/BMDL (caution)",
        "threshold": 3,
        "failure_bin": constants.BIN_WARNING,
        "enabled_nested": True,
        "enabled_continuous": True,
        "enabled_dichotomous": True,
    },
    "control_residual_high": {  # TODO residuals not available for cont
        "threshold": 2,
        "failure_bin": constants.BIN_WARNING,
        "enabled_nested": True,
        "enabled_continuous": False,
        "enabled_dichotomous": True,
    },
}

RULE_TYPES = {
    "gof": rules.GoodnessOfFit,
    "dof_zero": rules.NoDegreesOfFreedom,
    "high_bmd": rules.HighBmd,
    "warnings": rules.Warnings,
    "high_bmdl": rules.HighBmdl,
    "roi_large": rules.LargeRoi,
    "gof_cancer": rules.GoodnessOfFitCancer,
    "aic_missing": rules.AicExists,
    "bmd_missing": rules.BmdExists,
    "roi_missing": rules.RoiExists,
    "bmdl_missing": rules.BmdlExists,
    "bmdu_missing": rules.BmduExists,
    "low_bmd_fail": rules.LowBmd,
    "low_bmd_warn": rules.LowBmd,
    "variance_fit": rules.VarianceFit,
    "low_bmdl_fail": rules.LowBmdl,
    "low_bmdl_warn": rules.LowBmdl,
    "variance_type": rules.VarianceType,
    "control_stdev_fit": rules.ControlStdevFit,
    "bmd_bmdl_ratio_fail": rules.BmdBmdlRatio,
    "bmd_bmdl_ratio_warn": rules.BmdBmdlRatio,
    "control_residual_high": rules.HighControlRisidual,
}
