name: Lines of Code

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install and execute
        shell: bash
        run: |
          sudo apt-get install -y cloc
          make loc
      - name: Generate report
        run: |
          echo '# Lines of Code:\n\n' >> $GITHUB_STEP_SUMMARY
          cat loc.txt >> $GITHUB_STEP_SUMMARY
